#!/bin/bash
#SBATCH -J activeLearning15         # job name
#SBATCH -o activeLearning15.o%j       # output and error file name (%j expands to jobID)
#SBATCH -n 1              # total number of mpi tasks requested
#SBATCH -p gpu     # queue (partition) -- normal, development, etc.
#SBATCH -t 10:59:59        # run time (hh:mm:ss) - 1.0 hours
#SBATCH --mail-user=nahidcse05@gmail.com
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes

module load python

python activeCode.py TREC8 50 50 Basic